# Generated by Django 2.0.3 on 2018-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180417_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='valid',
            field=models.CharField(choices=[('u', '未审核'), ('s', '已审核'), ('f', '驳回')], default='u', max_length=1, verbose_name='审核状态'),
        ),
    ]
