# Generated by Django 2.0.3 on 2018-04-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_valid_comment', 'Can validation comment'),)},
        ),
    ]
